### ISSUE TITLE
`flutter_udid` does not specify a Swift version

### ISSUE THREAD

**Issue by marcosgallardo** [GigaDroid/flutter_udid#15]
When I try to run my app on iOS using `flutter build ios` I get this error:

> `flutter_udid` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please
>     contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Full output:

```
$ flutter build ios
Building com.usdentaldepot.masterdental for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: K85NPKGW53
Running pod install...                                              2.1s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A flutter_udid
      M Flutter
      - firebase_analytics
      - firebase_core
      - firebase_dynamic_links
      - flutter_secure_storage
      - flutter_webview_plugin
      - package_info
      - path_provider
      - screen
      - share
      - sqflite
      - url_launcher
      - video_player

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_dynamic_links` from `.symlinks/plugins/firebase_dynamic_links/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `flutter_udid` from `.symlinks/plugins/flutter_udid/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `screen` from `.symlinks/plugins/screen/ios`
    -> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A FMDB
      A Firebase
      A FirebaseAnalytics
      A FirebaseAnalyticsInterop
      A FirebaseCore
      A FirebaseDynamicLinks
      A FirebaseInstanceID
      A Flutter
      A GoogleAppMeasurement
      A GoogleUtilities
      A SAMKeychain
      A firebase_analytics
      A firebase_core
      A firebase_dynamic_links
      A flutter_secure_storage
      A flutter_udid
      A flutter_webview_plugin
      A nanopb
      A package_info
      A path_provider
      A screen
      A share
      A sqflite
      A url_launcher
      A video_player

    Downloading dependencies

    -> Installing FMDB (2.7.5)
      > Copying FMDB from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/FMDB/2.7.5-2ce00` to `Pods/FMDB`

    -> Installing Firebase (6.1.0)
      > Copying Firebase from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/Firebase/6.1.0-8d77b` to `Pods/Firebase`

    -> Installing FirebaseAnalytics (6.0.1)
      > Copying FirebaseAnalytics from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalytics/6.0.1-62930` to
      `Pods/FirebaseAnalytics`

    -> Installing FirebaseAnalyticsInterop (1.2.0)
      > Copying FirebaseAnalyticsInterop from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalyticsInterop/1.2.0-efbe4` to
      `Pods/FirebaseAnalyticsInterop`

    -> Installing FirebaseCore (6.0.1)
      > Copying FirebaseCore from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/FirebaseCore/6.0.1-66bde` to `Pods/FirebaseCore`

    -> Installing FirebaseDynamicLinks (4.0.0)
      > Copying FirebaseDynamicLinks from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/FirebaseDynamicLinks/4.0.0-25fc4` to
      `Pods/FirebaseDynamicLinks`

    -> Installing FirebaseInstanceID (4.1.0)
      > Copying FirebaseInstanceID from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/FirebaseInstanceID/4.1.0-27bed` to
      `Pods/FirebaseInstanceID`

    -> Installing Flutter (1.0.0)

    -> Installing GoogleAppMeasurement (6.0.1)
      > Copying GoogleAppMeasurement from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/GoogleAppMeasurement/6.0.1-51d8d` to
      `Pods/GoogleAppMeasurement`

    -> Installing GoogleUtilities (6.1.0)
      > Copying GoogleUtilities from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/GoogleUtilities/6.1.0-84df5` to
      `Pods/GoogleUtilities`

    -> Installing SAMKeychain (1.5.3)
      > Copying SAMKeychain from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/SAMKeychain/1.5.3-483e1` to `Pods/SAMKeychain`

    -> Installing firebase_analytics (0.0.1)
     > Running prepare command
       $ /bin/bash -c  set -e echo // Generated file, do not edit > Classes/UserAgent.h echo "#define LIBRARY_VERSION @\"5.0.2\"" >>
       Classes/UserAgent.h echo "#define LIBRARY_NAME @\"flutter-fire-analytics\"" >> Classes/UserAgent.h

    -> Installing firebase_core (0.0.1)
     > Running prepare command
       $ /bin/bash -c  set -e echo // Generated file, do not edit > Classes/UserAgent.h echo "#define LIBRARY_VERSION @\"0.4.0-9\"" >>
       Classes/UserAgent.h echo "#define LIBRARY_NAME @\"flutter-fire-core\"" >> Classes/UserAgent.h

    -> Installing firebase_dynamic_links (0.1.0)
     > Running prepare command
       $ /bin/bash -c  set -e echo // Generated file, do not edit > Classes/UserAgent.h echo "#define LIBRARY_VERSION @\"0.5.0-1\"" >>
       Classes/UserAgent.h echo "#define LIBRARY_NAME @\"flutter-fire-dl\"" >> Classes/UserAgent.h

    -> Installing flutter_secure_storage (3.3.1)

    -> Installing flutter_udid (0.0.1)

    -> Installing flutter_webview_plugin (0.0.1)

    -> Installing nanopb (0.3.901)
      > Copying nanopb from `/Users/marcosgallardo/Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f` to `Pods/nanopb`

    -> Installing package_info (0.0.1)

    -> Installing path_provider (0.0.1)

    -> Installing screen (0.0.1)

    -> Installing share (0.5.2)

    -> Installing sqflite (0.0.1)

    -> Installing url_launcher (0.0.1)

    -> Installing video_player (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `flutter_udid` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please
    contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:115:in
    `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-AR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

Hope you can help me.
Thanks.

**Comment by joaoaaires** [comment]
Hey, me too

**Comment by ethanliew** [comment]
me too

**Comment by GigaDroid** [comment]
The latest release now specifies a Swift version, which should fix this problem.
Please give this a try and reopen this issue in case there is still a problem
