### ISSUE TITLE
[v1.1.0] Crash on Android in onDetachedFromEngine()

### ISSUE THREAD

**Issue by dupovalo** [GigaDroid/flutter_udid#25]
Hi,

Thank you for the great plugin. It's super helpful.

For the topic:
The crash happens when you close the app (i.e. destroy its main activity).
From what I can find, the _channel_ property seems never used (local variable is used instead).
Here is a stacktrace:

> FATAL EXCEPTION: main
Process: com.example.app, PID: 25611
java.lang.RuntimeException: **Unable to destroy activity {com.example.app/com.example.app.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property channel has not been initialized**
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4480)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4498)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
**Caused by: kotlin.UninitializedPropertyAccessException: lateinit property channel has not been initialized
	at de.gigadroid.flutterudid.FlutterUdidPlugin.onDetachedFromEngine(FlutterUdidPlugin.kt:56)**
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:262)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:278)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:122)
	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:434)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:576)
	at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:587)
	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:608)
	at android.app.Activity.performDestroy(Activity.java:7395)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4465)
	... 11 more

**Comment by GigaDroid** [comment]
Thanks for reporting this! Should be fixed in 1.2.0
